spring:
  application:
    name: identity-service
  datasource:
    url: ${IDENTITY_DATASOURCE_URL:jdbc:postgresql://localhost:5432/identity_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgrespassword}
  jpa:
    open-in-view: false
    hibernate:
      # Flyway quan ly schema -> Ngay 4 doi thanh 'validate' khi da co entity + migration.
      ddl-auto: validate
  flyway:
    # Ngay 4: bat len khi da co file migration dau tien trong db/migration.
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${IDENTITY_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000} # 15 minutes (ms)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days (ms)
