plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
    id 'com.google.protobuf' version '0.9.4'
}

description = 'grpc-api'

dependencyManagement {
    imports {
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}

dependencies {
    api 'io.grpc:grpc-stub'
    api 'io.grpc:grpc-protobuf'
    api 'com.google.protobuf:protobuf-java'
    compileOnly 'org.apache.tomcat:annotations-api:6.0.53'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.5'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.68.1'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                grpc {}
            }
        }
    }
}
